package sample.oracle.otn.soascheduler.proxy;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

public class HelloWorld_ptClient
{
  @WebServiceRef
  private static Helloworld_client_ep helloworld_client_ep;

    public static void main(String [] args)
    {
    helloworld_client_ep = new Helloworld_client_ep();
    HelloWorld helloWorldProcess = helloworld_client_ep.getHelloWorld_pt();
    // Add your code to call the desired methods.
    System.out.println(helloWorldProcess.process("myx"));
    }

}
